// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart'
 show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyLXj7dVuMeLPrkVpnFI6mLOZdSKlG0o4',
    appId: '1:1093175649567:web:573c1fbf0a60b4f8d7fc2a',
    messagingSenderId: '1093175649567',
    projectId: 'docsaverapp-ca86e',
    authDomain: 'docsaverapp-ca86e.firebaseapp.com',
    storageBucket: 'docsaverapp-ca86e.appspot.com',
    measurementId: 'G-4SK3D1NNWM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRsv_exHCXK0YsuPir7TxrNZVjY_sv3gw',
    appId: '1:1093175649567:android:22727617d9b02e17d7fc2a',
    messagingSenderId: '1093175649567',
    projectId: 'docsaverapp-ca86e',
    storageBucket: 'docsaverapp-ca86e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBL78OP1uMmXd6AqXizB8cl2-ZMaUXUUvs',
    appId: '1:1093175649567:ios:9965fc59ddeac701d7fc2a',
    messagingSenderId: '1093175649567',
    projectId: 'docsaverapp-ca86e',
    storageBucket: 'docsaverapp-ca86e.appspot.com',
    iosBundleId: 'com.example.documentSaverApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBL78OP1uMmXd6AqXizB8cl2-ZMaUXUUvs',
    appId: '1:1093175649567:ios:9965fc59ddeac701d7fc2a',
    messagingSenderId: '1093175649567',
    projectId: 'docsaverapp-ca86e',
    storageBucket: 'docsaverapp-ca86e.appspot.com',
    iosBundleId: 'com.example.documentSaverApplication',
  );
}
